/**
 * Shared phrase lists. Sites add extras via createSubmitFormHandler({ extraHardTerms, extraScoreTerms }).
 * Matching is case-insensitive after punctuation is stripped to spaces.
 */

export const HARD_SPAM_TERMS: readonly string[] = [
  "seo report",
  "seo strategy",
  "seo services",
  "seo specialist",
  "seo expert",
  "seo audit",
  "search engine optimisation",
  "search engine optimization",
  "digital marketing",
  "digital marketing manager",
  "guest post",
  "domain authority",
  "dr 50",
  "backlink",
  "cold outreach",
  "reddit demand",
  "real reddit conversations",
  "monitoring relevant subreddits",
  "warm inbound interest",
  "proposal package",
  "if this is relevant for you",
  "if my previous email didn t go through",
  "if your previous email didn t go through",
  "if you're not interested",
  "if you re not interested",
  'send us "no"',
  "send us no",
  "motivated clients",
  "ethical strategies to draw",
  "social media content",
  "ready to post social media content",
  "7 days of posting content for free",
  "internet marketing warlock",
  "creating money out of thin air",
  "hidden money",
  "trigger points",
  "sell to the affluent",
  "escort application",
  "spellpros com",
  "unsubscribe",
  "trustpilot",
  "fake reviews",
  "purchase reviews",
  "buy reviews",
  "buy google reviews",
  "verified reviews package",
  "reputation repair service",
  "reputation management",
  "manage your online reputation",
  "suppress negative reviews",
  "negative review removal",
  "remove negative reviews",
  "remove bad reviews",
  "selling your business",
  "sell your business",
  "business broker",
  "interested in selling",
  "buying plumbing businesses",
  "buying businesses in your industry",
  "quantity takeoff",
  "stop to opt out",
  "seo opportunities",
  "electrical estimating",
  "project estimator",
];

export const SCORE_SPAM_TERMS: readonly string[] = [
  "search results",
  "rankings",
  "online presence",
  "visibility on google",
  "search visibility",
  "organic traffic",
  "relevant traffic",
  "convenient time to connect",
  "let me know a convenient time",
  "i recently came across your website",
  "came across your website",
  "came across your business",
  "i noticed your website",
  "pricing and packages",
  "my services and pricing",
  "leads",
  "learn more",
  "book a call",
  "operational systems",
  "day to day workflows",
  "specific examples",
  "high quality email list",
  "free posting content",
  "local business owners",
  "show up online",
  "quote/package/proposal",
  "brand-safe",
  "aged-account",
  "b2b",
  "saas",
  "high-intent threads",
  "google reviews",
  "yelp reviews",
  "tripadvisor reviews",
  "review building",
  "boost your reviews",
  "improve your reviews",
  "more reviews for",
  "positive reviews package",
  "ratings and reviews",
  "reviews for your business",
  "reply yes",
  "vas 4 hire",
  "vas4hire",
  "takeoff services",
  "senior estimator",
  "hope you re doing well",
  "reaching out here",
  "tried emailing but",
  "office side of the business",
  "best regards",
];
